### ISSUE TITLE
Girlstats

### ISSUE THREAD

**Issue by annielegge** [gabrielkrieshok/ict4dguide#2]
Gender / Websites
The interactive platform offers global data on adolescent girls and young women (aged 15-24) across issues such as health, education and labour market participation. This data enables businesses to identify gaps and understand where their engagement will have the most positive impact. 
https://girl-stats.org/

**Comment by gabrielkrieshok** [comment]
Better late than never -- I'm adding this to the new/updated materials -- thanks!
