### ISSUE TITLE
Every1Mobile

### ISSUE THREAD

**Issue by LiezeLangford** [gabrielkrieshok/ict4dguide#7]
Every1Mobile is a digital and mobile services provider dedicated to improving lives through digital solutions - at scale. Founded in 2010, we have led and supported more than 50 projects in multiple sub-Saharan countries for clients and funders including Unilever, DFID, USAID, Gates Foundation, the UN,  the World bank, ONE, Old Mutual, Mozilla Foundation and the EU.   We are proud to be identified by the U.K. Department for International Development (DFID) as one of three UK “cutting edge” Small and Medium Sized Enterprises (SMEs). 

https://www.every1mobile.com/

**Comment by gabrielkrieshok** [comment]
Hi Lieze -- thanks for the input! I am actually migrating all of the links over to the (much simpler) [Techf4goodResources](https://github.com/gabrielkrieshok/tech4goodresources/) page. And I've added Every1Mobile! : )

**Comment by LiezeLangford** [comment]
HI Gabriel,

Thanks! A really useful page.
LIEZE LANGFORD
International Communication Manager
Brighton, UK

t: +44 (0) 7791 950625 <+447791950625>
e: lieze@every1mobile.com
s: lieze.langford

www.every1mobile.com
[image: Every1Mobile] <https://www.every1mobile.com/>

Make sure you subscribe to our newsletter here
<https://www.every1mobile.com/sign-up-to-our-newsletter/>
